#Format alert body
alertText="$HOSTNAME NIC unregistered!"
#Webhook URL. Replace with your URL generated by teams. Follow this KB to generate a webhook URL https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook?tabs=dotnet
webhookURL="https://f5.webhook.office.com/webhookb2/"
#Senc Alert. 
curl -d '{"text":"'"$alertText"'"}' -H 'Content-Type: application/json' $webhookURL
